version: "3.11"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE} # This will point to .env.development or .env.production
    depends_on:
      - db
  scheduler:
    build: .
    command: >
      sh -c "
        while true; do
          python manage.py sync_cnbc_rss --limit 50 || true;
          sleep 300;
        done
      "
    env_file:
      - ${ENV_FILE}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    env_file:
      - ${ENV_FILE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
