# Generated by Django 5.2.5 on 2025-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('homepage', models.URLField(max_length=500)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='news_logos/')),
            ],
        ),
    ]
