# Generated by Django 5.2.5 on 2025-08-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssource',
            name='logo_img',
        ),
    ]
