# Generated by Django 5.2.5 on 2025-08-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_newssource_logo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('sentiment', models.CharField(blank=True, choices=[(1, 'Positive'), (2, 'Neutral'), (3, 'Negative')], db_index=True, max_length=8)),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='api.newssource')),
            ],
        ),
    ]
