# Generated by Django 5.2.5 on 2025-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sentiment',
            field=models.CharField(blank=True, choices=[(1, 'Positive'), (2, 'Neutral'), (3, 'Negative')], db_index=True, max_length=8, null=True),
        ),
    ]
