# Generated by Django 5.2.5 on 2025-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_news_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sentiment',
            field=models.IntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Neutral'), (3, 'Negative')], db_index=True, max_length=8, null=True),
        ),
    ]
