# Generated by Django 5.2.5 on 2025-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_news_link_alter_news_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
