# Generated by Django 5.2.5 on 2025-08-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_news_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
