# Generated by Django 5.2.5 on 2025-08-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_news_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='api.newssource'),
        ),
    ]
